### PR TITLE
check for invalid column and table names

### LINKED ISSUE #18: Error if column names start with digits
If the column names of a table start with digits, the tool fails to create the struct.
```
> processing table "MyTable"
        > number of columns: 4
                > id
                > name
                > 1person
                > 2person

run error: could not create struct file for table MyTable: could not format file /home/ronnie/project/models/MyTable.go: 12:1: expected '}', found 1% 
```
I'm not sure what the best thing to do here would be. I _know_ it's bad practice to have SQL column names start with numbers but it's technically allowed. So we may have to deal with it if we don't have authority to change the actual database schema.

But Golang obviously doesn't allow fieldnames to start with numbers, so what would be a sensible thing to do?
- Prefix them with a letter? `x1person`
- Swap the digits to the end? `person1`

This may open up a whole can of worms because [MySQL table and column names can be full unicode](https://dev.mysql.com/doc/refman/8.0/en/identifiers.html) but [Go only allows letters, underscore, and digits](https://golang.org/ref/spec#Identifiers), and each identifier has to start with a letter or underscore.

Then again, it is really absurd to use non-letter characters in table and column names, so it would probably be fair enough to just not deal with them.

### PR DESCRIPTION
**Pull request by ronniegane**
resolves #18 
This now does the following:
- Replaces any whitespace in table or column names with underscores.
- Checks for any characters in table or column names that aren't valid Go identifiers (allows Unicode letters, digits and underscores), and throws an error if it finds them.
This is built on top of the branch for #19 so that you can ignore these errors if you want to.

### CODE REVIEW

File: internal/cli/tables-to-go-cli.go [hunk 1]
```diff
@@ -45,18 +46,32 @@ func Run(settings *settings.Settings, db database.Database, out output.Writer) (
 		}
 
 		if err = db.GetColumnsOfTable(table); err != nil {
-			return fmt.Errorf("could not get columns of table %s: %v", table.Name, err)
+			if !settings.Force {
+				return fmt.Errorf("could not get columns of table %s: %v", table.Name, err)
+			}
+			fmt.Printf("could not get columns of table %s: %v\n", table.Name, err)
```
Comment (fraenky8) [inline internal/cli/tables-to-go-cli.go]: Lets use `%q` here for table name format string.

Comment (fraenky8) [inline internal/cli/tables-to-go-cli.go]: Lets use %q here for table name format string - applies also for all other error messages.

File: internal/cli/tables-to-go-cli.go [hunk 2]
```diff
@@ -76,23 +91,48 @@ func (c columnInfo) hasTrue() bool {
...
+	tableName := strings.Title(settings.Prefix + table.Name + settings.Suffix)
+	// Replace any whitespace with underscores
+	tableName = strings.Map(replaceSpace, tableName)
+	if settings.IsOutputFormatCamelCase() {
+		tableName = camelCaseString(tableName)
+	}
+
+	// Check that the table name doesn't contain any invalid characters for Go variables
+	if !validVariableName(tableName) {
+		return "", "", fmt.Errorf("Table name %q contains invalid characters", table.Name)
```
Comment (fraenky8) [inline internal/cli/tables-to-go-cli.go]: Error strings should not be capitalized.

File: internal/cli/tables-to-go-cli.go [hunk 3]
```diff
@@ -76,23 +91,48 @@ func (c columnInfo) hasTrue() bool {
...
-			columnName = camelCaseString(column.Name)
+			columnName = camelCaseString(columnName)
 		}
 		if settings.ShouldInitialism() {
 			columnName = toInitialisms(columnName)
 		}
 
+		// Check that the column name doesn't contain any invalid characters for Go variables
+		if !validVariableName(columnName) {
+			return "", "", fmt.Errorf("Column name %q in table %q contains invalid characters", column.Name, table.Name)
```
Comment (fraenky8) [inline internal/cli/tables-to-go-cli.go]: Error strings should not be capitalized.

File: internal/cli/tables-to-go-cli.go [hunk 4]
```diff
@@ -274,3 +309,23 @@ func indexCaseInsensitive(s, substr string) int {
 	s, substr = strings.ToLower(s), strings.ToLower(substr)
 	return strings.Index(s, substr)
 }
+
+// ValidVariableName checks for the existence of any characters
+// outside of Unicode letters, numbers and underscore.
+func validVariableName(str string) bool {
```
Comment (fraenky8) [inline internal/cli/tables-to-go-cli.go]: Altough it's a private function we should provide some unit tests for it.

Can we use `s` instead if `str` as parameter name?

Comment (ronniegane) [reply internal/cli/tables-to-go-cli.go]: Tests added in e954a4472d and 809e9861ff8
Parameter name changed in ef3a47706c65

File: internal/cli/tables-to-go-cli.go (hunk 3 above)
Comment (ronniegane) [reply internal/cli/tables-to-go-cli.go]: resolved in 396b9e869b39

File: internal/cli/tables-to-go-cli.go (hunk 2 above)
Comment (ronniegane) [reply internal/cli/tables-to-go-cli.go]: resolved in 396b9e8

File: internal/cli/tables-to-go-cli.go (hunk 1 above)
Comment (ronniegane) [reply internal/cli/tables-to-go-cli.go]: resolved in 396b9e869b3

**Comment by ronniegane** [comment]
I pulled the column formatting out into a function that is easy to unit test: 719aecfbdaa7
That seemed simpler than having to set up tables and DBs.
The test cases show how the columns will be formatted, @fraenky8 can you check that those have the desired behaviour for original and camelcase?

Do you want me to rename *table* names that start with numbers as well? At the moment it's only renaming columns.

File: internal/cli/tables-to-go-cli.go [hunk 5]
```diff
@@ -329,3 +311,43 @@ func replaceSpace(r rune) rune {
...
+func formatColumnName(settings *settings.Settings, column, table string) (string, error) {
+
+	// Columns that don't start with a capital letter must have one prefixed
+	// to be public fields
+	var prefix string
+	if settings.IsOutputFormatCamelCase() {
+		prefix = "X"
+	} else {
+		prefix = "X_"
+	}
```
Comment (fraenky8) [inline internal/cli/tables-to-go-cli.go]: Can you move the `prefix` creation more to the place (line 343) where it's actually used? Also using `else` is not necassary, we can stick to our default OutputFormat (camelCase) and rewrite it like

```go
prefix := "X"
if !settings.IsOutputFormatCamelCase() {
	prefix = "X_"
}
```

Maybe for the sake of clean code we can introduce a new method in settings `IsOutputFormatOriginal` to get rid of the negation in the if-statement - but not necessary!

Comment (ronniegane) [reply internal/cli/tables-to-go-cli.go]: Moved the creation in 584dbfa and I changed the logic to avoid the negation:
```go
prefix := "X_"
if settings.IsOutputFormatCamelCase() {
	prefix = "X"
}
```
